<a href="https://colab.research.google.com/github/fahadfakrul/Python-1.0/blob/main/Packages.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

popular python packages
https://www.mygreatlearning.com/blog/open-source-python-libraries/

https://pip.pypa.io/en/stable/installation/  for local installation library

In [1]:
# Import the math package
import math

# Calculate C
C = 2 * 0.43 * math.pi

# Calculate A
A = math.pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [2]:
# Import pi function of math package
from math import pi

# Calculate C
C = 2 * 0.43 * pi

# Calculate A
A = pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


NumPy

In [3]:
# Import the numpy package as np
import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [6]:
# Import numpy
import numpy as np

height_in = [170, 169.5, 154, ]
# Create a numpy array from height_in: np_height_in
np_height_in= np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[170.  169.5 154. ]
[4.318  4.3053 3.9116]


numpy arrays cannot contain elements with different types. Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

In [7]:

print(np.array([True, 1, 2]) + np.array([3, 4, False]))

print(np.array([True, 1, 2, 3, 4, False]))

print(np.array([4, 3, 0]) + np.array([0, 2, 2]))

print(np.array([0, 1, 2, 3, 4, 5]))

print(np.array([1, 1, 2]) + np.array([3, 4, -1]))



[4 5 2]
[1 1 2 3 4 0]
[4 5 2]
[0 1 2 3 4 5]
[4 5 1]


In [9]:
import numpy as np
import random

# Generate 150 random weights (in pounds) and heights (in inches)
weight_lb = [random.randint(45, 120) for _ in range(150)]
height_lb = [random.randint(150, 200) for _ in range(150)]

# Convert the lists to numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_lb = np.array(height_lb)  # corrected the name

# Print out the weight at index 50
print("Weight at index 50:", np_weight_lb[50])

# Print out sub-array of np_height_lb: index 100 up to and including index 110
print("Height from index 100 to 110:", np_height_lb[100:111])

Weight at index 50: 98
Height from index 100 to 110: [162 180 171 183 189 153 152 152 171 181 198]


2D NumPy Arrays

In [10]:
import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [11]:
# import numpy as np

# np_baseball = np.array(baseball)

# # Print out the 50th row of np_baseball
# print(np_baseball[49,:])

# # Select the entire second column of np_baseball: np_weight_lb
# np_weight_lb=np_baseball[:,1]

# # Print out height of 124th player
# np_height_lb=np_baseball[123,0]
# print(np_height_lb)

In [12]:
# import numpy as np

# np_baseball = np.array(baseball)

# # Print out addition of np_baseball and updated
# print(np_baseball+updated)

# # Create numpy array: conversion
# conversion=np.array([0.0254,0.453592,1])

# # Print out product of np_baseball and conversion
# print(np_baseball*conversion)

NumPy: Basic Statistics

In [1]:
# import numpy as np

# # Create np_height_in from np_baseball
# np_height_in = np_baseball[:, 0]

# # Print out the mean of np_height_in
# print(np.mean(np_height_in))

# # Print out the median of np_height_in
# print(np.median(np_height_in))
# https://numpy.org/devdocs/reference/routines.statistics.html